# Generated by Django 5.0.6 on 2024-08-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password1', models.CharField(blank=True, max_length=30)),
                ('password2', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
